apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: ops-pilot-hpa
  namespace: ops-pilot

  labels:
    app: ops-pilot
    component: autoscaling

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ops-pilot

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70