apiVersion: v1
kind: Secret

metadata:
  name: ops-pilot-secret
  namespace: ops-pilot

  labels:
    app: ops-pilot
    component: secret

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres